name: secrets-manager
channels:
  - defaults
dependencies:
  - _libgcc_mutex=0.1
  - ca-certificates=2021.1.19
  - certifi=2020.12.5
  - ld_impl_linux-64=2.33.1
  - libedit=3.1.20191231
  - libffi=3.3
  - libgcc-ng=9.1.0
  - libstdcxx-ng=9.1.0
  - ncurses=6.2
  - openssl=1.1.1i
  - pip=20.3.3
  - python=3.9.1
  - readline=8.1
  - setuptools=52.0.0
  - sqlite=3.33.0
  - tk=8.6.10
  - tzdata=2020f
  - wheel=0.36.2
  - xz=5.2.5
  - zlib=1.2.11
  - pip:
    - bcrypt==3.2.0
    - cffi==1.14.5
    - cryptography==3.4.5
    - loguru==0.5.3
    - pycparser==2.20
    - six==1.15.0
